[build]
  command = "npm install && npm run build"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD ./"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://ai-dashboard-kclam888.netlify.app"
  NEXTAUTH_URL = "https://ai-dashboard-kclam888.netlify.app"
  NODE_VERSION = "18"
  NEXTAUTH_SECRET = "CACROatrxfJ7aZNAf5e0rrKtNMQkpt9r/zPD+Nuqf6E="
  NEXT_PUBLIC_GOOGLE_CLIENT_ID = "${env:NEXT_PUBLIC_GOOGLE_CLIENT_ID}"
  GOOGLE_CLIENT_SECRET = "${env:GOOGLE_CLIENT_SECRET}"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs-server"
  status = 200
  force = true

[functions]
  node_bundler = "esbuild"
  included_files = ["prisma/**/*"]