[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://your-site.netlify.app"
  NEXTAUTH_URL = "https://your-site.netlify.app"